import { Activity } from "@components/ActivitiesList/ActivitiesList";

export const ACTIVITIES_MOCK: Activity[] = [
  {
    id: 1,
    name: "Death on the Nile",
    description:
      "Watch a movie starring Kenneth Branaugh about solving a murder mystery.",
    voteCountUp: 2,
    voteCountDown: 0,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 2,
    name: "Make Pasta",
    description:
      "Make pasta from scratch using flour and egg. Then cook and use favorite sauce.",
    voteCountUp: 2,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 3,
    name: "Swim 10 laps",
    description: "Swim 10 laps in the pool.",
    voteCountUp: 0,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor/Outdoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 4,
    name: "Wedding Crasher",
    description: "Go to a random wedding and crash",
    voteCountUp: 4,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 5,
    name: "Netflix and Relax",
    description:
      "Pick a movie on Netflix and relax. No discration. You can also discuss the movie like pretentious intellectuals.",
    voteCountUp: 1,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 6,
    name: "Play musical instruments",
    description: "Learn an instrument of choice and jam together.",
    voteCountUp: 3,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 7,
    name: "Batting Cage Therapy",
    description: "Go to a batting cage and hit your problems away.",
    voteCountUp: 2,
    voteCountDown: 1,
    memberCount: 2,
    category: "Outdoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 8,
    name: "Kayaking",
    description: "Relax on a nice sunny day with a trip down the river.",
    voteCount: 4,
    category: "outdoor",
  },

  {
    id: 9,
    name: "Movies",
    description:
      "If the weather is bad outside, enjoy a cozy movie in a movie theater.",
    voteCount: 2,
    category: "indoor",
  },
  {
    id: 10,
    name: "Fondue",
    description:
      "If you enjoy cooking, try making fondue as a romantic activity.",
    voteCount: 2,
    category: "indoor",
  },
  {
    id: 11,
    name: "Hiking",
    description: "An outdoor activity your friends will enjoy.",
    voteCount: 6,
    category: "outdoor",
  },
  {
    id: 12,
    name: "Salsa Class",
    description:
      "Learn a new dance and meet new people by attending a salsa class.",
    voteCount: 4,
    category: "indoor",
  },
  {
    id: 13,
    name: "Hiking",
    description: "Enjoy a day in nature.",
    voteCount: 0,
    category: "Outdoor",
  },
  {
    id: 14,
    name: "Cooking Class",
    description: "Learn to cook delicious dishes.",
    voteCount: 0,
    category: "Indoor",
  },
  {
    id: 15,
    name: "Movie Night",
    description: "Watch a favorite movie together.",
    voteCount: 0,
    category: "Indoor",
  },
  {
    id: 16,
    name: "Beach Picnic",
    description: "Relax by the seaside with a picnic.",
    voteCount: 0,
    category: "Outdoor",
  },
  {
    id: 17,
    name: "Board Games Night",
    description: "Play fun board games with friends.",
    voteCount: 0,
    category: "Indoor",
  },
];
