import ActivitiesList from "./ActivitiesList";

const act_list = [
  {
    id: 1,
    name: "Death on the Nile",
    description:
      "Watch a movie starring Kenneth Branaugh about solving a murder mystery.",
    voteCountUp: 2,
    voteCountDown: 0,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 2,
    name: "Make Pasta",
    description:
      "Make pasta from scratch using flour and egg. Then cook and use favorite sauce.",
    voteCountUp: 2,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 3,
    name: "Swim 10 laps",
    description: "Swim 10 laps in the pool.",
    voteCountUp: 0,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor/Outdoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 4,
    name: "Wedding Crasher",
    description: "Go to a random wedding and crash",
    voteCountUp: 4,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 5,
    name: "Netflix and Relax",
    description:
      "Pick a movie on Netflix and relax. No discration. You can also discuss the movie like pretentious intellectuals.",
    voteCountUp: 1,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 6,
    name: "Play musical instruments",
    description: "Learn an instrument of choice and jam together.",
    voteCountUp: 3,
    voteCountDown: 1,
    memberCount: 2,
    category: "Indoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
  {
    id: 7,
    name: "Batting Cage Therapy",
    description: "Go to a batting cage and hit your problems away.",
    voteCountUp: 2,
    voteCountDown: 1,
    memberCount: 2,
    category: "Outdoor",
    location: "My place",
    date: "2023-05-11",
    timeStart: "7:30 PM",
    timeEnd: "10:00 PM",
  },
];

export default function Activities() {
  return <ActivitiesList list={act_list} />;
}
